// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using codefistactivity1.models;

#nullable disable

namespace codefistactivity1.Migrations
{
    [DbContext(typeof(studentappdbcontext))]
    [Migration("20251031062647_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("codefistactivity1.models.mark", b =>
                {
                    b.Property<int>("markid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("markid"));

                    b.Property<int>("m1")
                        .HasColumnType("int");

                    b.Property<int>("m2")
                        .HasColumnType("int");

                    b.Property<int>("m3")
                        .HasColumnType("int");

                    b.Property<int>("stdudentid")
                        .HasColumnType("int");

                    b.Property<int>("studentsid")
                        .HasColumnType("int");

                    b.HasKey("markid");

                    b.HasIndex("studentsid");

                    b.ToTable("marks");
                });

            modelBuilder.Entity("codefistactivity1.models.students", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("mobileno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("codefistactivity1.models.mark", b =>
                {
                    b.HasOne("codefistactivity1.models.students", "students")
                        .WithMany("marks")
                        .HasForeignKey("studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("students");
                });

            modelBuilder.Entity("codefistactivity1.models.students", b =>
                {
                    b.Navigation("marks");
                });
#pragma warning restore 612, 618
        }
    }
}
